import Foundation

public enum DanceCatalog {
    public static let contentNotice = "以下为本应用编写的基础练习提示，不是授权视频示范，也不是经过教练验证的课程。动作名和风格归属仅用于学习导航；BPM 是可调整的练习起点。出现疼痛或眩晕时停止；更复杂动作请向合格教师学习。"

    public static let moves: [DanceMove] = [
        DanceMove(id: "hiphop-bounce", name: "基础上下律动", englishName: "Bounce", style: .hipHop,
                  summary: "让膝盖与重心轻轻随拍起伏，先找到持续而舒适的律动。",
                  cues: ["双脚约与髋同宽，膝盖保持柔软", "随拍轻屈膝，再回到自然站姿", "保持呼吸，用小幅度找到均匀节奏"],
                  commonMistakes: ["膝盖锁死或蹲得过深", "只动肩膀，重心没有跟随"], bpmMin: 65, bpmMax: 100),
        DanceMove(id: "hiphop-rock", name: "前后重心律动", englishName: "Rock", style: .hipHop,
                  summary: "在稳定站姿中探索小幅度前后重心变化。",
                  cues: ["保持双脚着地，先把移动幅度缩小", "让胸廓与重心一起前后回应音乐", "每次转换都保持能够随时停下的平衡"],
                  commonMistakes: ["重心超出支撑范围", "用腰部猛烈折叠代替全身律动"], bpmMin: 60, bpmMax: 95),
        DanceMove(id: "hiphop-step-touch", name: "侧步点地", englishName: "Step Touch", style: .hipHop,
                  summary: "向侧方迈一步，另一只脚轻点靠近，再换方向。",
                  cues: ["先向右迈小步，左脚轻点靠近", "向左重复，膝盖跟随脚尖方向", "熟悉后加入柔和上下律动"],
                  commonMistakes: ["步幅太大而失去节奏", "点地脚过早承重"], bpmMin: 65, bpmMax: 110),
        DanceMove(id: "hiphop-two-step", name: "双步变化", englishName: "Two-Step Practice", style: .hipHop,
                  summary: "在侧步点地基础上安排两次方向变化，练习步伐和重心衔接。",
                  cues: ["先用口令标记每一步落点", "把重心交给支撑脚再移动另一脚", "保持基础律动，先不添加转身"],
                  commonMistakes: ["脚先跑走而重心留在原处", "为了追拍跨出过大的步幅"],
                  bpmMin: 70, bpmMax: 110, prerequisites: ["hiphop-step-touch"]),
        DanceMove(id: "hiphop-running-man", name: "奔跑步分解", englishName: "Running Man Preparation", style: .hipHop, level: 2,
                  summary: "把抬脚和另一脚后移拆开练习；这是低速准备练习，尚未包含完整弹跳。",
                  cues: ["扶稳或先单独练习小幅抬膝", "脚落地后再小幅移动另一只脚", "先离开音乐慢练，避免在粘滞地面强行滑脚"],
                  commonMistakes: ["在基础不稳时加入连续跳跃", "支撑膝内扣或落地过重"],
                  bpmMin: 65, bpmMax: 90, prerequisites: ["hiphop-bounce", "hiphop-step-touch"], impact: .moderate),
        DanceMove(id: "hiphop-party-groove", name: "派对律动组合", englishName: "Party Groove Practice", style: .hipHop,
                  summary: "把已熟悉的 Bounce 和侧步组织成轻松重复的基础组合。",
                  cues: ["用四拍原地律动，再用四拍侧步", "手臂自然摆动，保持自己的舒适范围", "动作记不住时回到 Bounce"],
                  commonMistakes: ["每拍都换新动作而忘记持续律动", "手臂用力过度"],
                  bpmMin: 70, bpmMax: 105, prerequisites: ["hiphop-bounce", "hiphop-step-touch"]),
        DanceMove(id: "hiphop-arm-groove", name: "手臂与律动协调", englishName: "Arm Groove Practice", style: .hipHop,
                  summary: "在小幅上下律动中加入自然手臂摆动，练习上下肢协调。",
                  cues: ["先保持四拍稳定的 Bounce", "增加轻松的前后摆臂", "肩部放松，手臂不必抬高"],
                  commonMistakes: ["加入手臂后下肢停拍", "耸肩或屏住呼吸"],
                  bpmMin: 65, bpmMax: 100, prerequisites: ["hiphop-bounce"]),
        DanceMove(id: "popping-isolation", name: "胸肩分离练习", englishName: "Upper-Body Isolation", style: .popping,
                  summary: "在舒适幅度内分别移动胸廓和肩部，建立对身体部位的感知。",
                  cues: ["保持膝盖柔软和自然站姿", "一次只尝试一个部位的小幅移动", "每次移动后回到自然位置"],
                  commonMistakes: ["靠后仰腰部追求大幅度", "同时移动所有部位"], bpmMin: 50, bpmMax: 80),
        DanceMove(id: "popping-arm-wave", name: "手臂波浪分解", englishName: "Arm Wave Preparation", style: .popping, level: 2,
                  summary: "逐段连接手腕、肘部与肩部的小幅变化，练习连续传递。",
                  cues: ["先缓慢区分手腕、肘部、肩部的位置", "关节保持在舒适活动范围内", "逐段连接，熟悉后再跟慢拍"],
                  commonMistakes: ["用力压腕或反折肘部", "为追求波浪形状而过度耸肩"],
                  bpmMin: 50, bpmMax: 80, prerequisites: ["popping-isolation"]),
        DanceMove(id: "popping-dime-stop", name: "轻柔停顿控制", englishName: "Dime Stop Preparation", style: .popping,
                  summary: "在小幅连续移动中加入明确停止，练习动与停的对比。",
                  cues: ["先做舒适的小幅前臂移动", "选定一拍停下，再放松恢复", "停止时不锁死关节，也不憋气"],
                  commonMistakes: ["用猛烈甩动制造停顿", "把持续紧张当成控制"], bpmMin: 55, bpmMax: 90),
        DanceMove(id: "popping-hand-path", name: "手部路径控制", englishName: "Hand Path Control", style: .popping,
                  summary: "让手在胸前沿简单直线和弧线缓慢移动，观察路径是否稳定。",
                  cues: ["选择胸前一段容易观察的路径", "以四拍移动、四拍返回", "肩部放松，手腕保持自然"],
                  commonMistakes: ["路径越做越大", "为了保持直线而僵硬用力"], bpmMin: 50, bpmMax: 85),
        DanceMove(id: "locking-point", name: "指向基础", englishName: "Point Preparation", style: .locking,
                  summary: "用清晰的手臂指向和短暂停留探索节奏表达。",
                  cues: ["站稳后向舒适方向轻轻伸出手臂", "肘部留有余量，视线可自然跟随", "回到放松位置，再换侧重复"],
                  commonMistakes: ["甩直肘关节", "指向时身体倾斜失去平衡"], bpmMin: 65, bpmMax: 100),
        DanceMove(id: "locking-lock", name: "锁定姿态准备", englishName: "Lock Position Preparation", style: .locking,
                  summary: "练习放松与短暂停留之间的变化，只使用小幅站立姿态。",
                  cues: ["以小幅屈膝开始，不做深蹲", "轻收手臂并短暂停留", "回到自然站姿，让停顿与音乐呼应"],
                  commonMistakes: ["用腰背猛烈折叠", "把锁定理解为关节强行锁死"],
                  bpmMin: 60, bpmMax: 95, prerequisites: ["locking-point"]),
        DanceMove(id: "house-jack", name: "Jack 律动准备", englishName: "Jack Preparation", style: .house,
                  summary: "用轻柔膝屈伸带动躯干起伏，探索 House 的持续律动。",
                  cues: ["双脚稳定，先从小幅膝盖起伏开始", "让躯干自然参与，避免刻意折腰", "呼吸持续，先慢速理解再加快"],
                  commonMistakes: ["只甩头或只折腰", "膝盖过深而无法连续跟拍"], bpmMin: 70, bpmMax: 105),
        DanceMove(id: "house-side-step", name: "侧向重心练习", englishName: "House Side-Step Preparation", style: .house,
                  summary: "把小幅侧步与持续躯干律动连接，先练稳重心转移。",
                  cues: ["左右交替迈小步", "脚落稳后再移动重心", "保留柔和 Jack，不加入交叉转身"],
                  commonMistakes: ["脚步加快后躯干停顿", "侧步跨得过大"],
                  bpmMin: 75, bpmMax: 110, prerequisites: ["house-jack"]),
        DanceMove(id: "house-weight-shift", name: "脚跟轻提与换重心", englishName: "House Weight-Shift Preparation", style: .house,
                  summary: "在脚尖仍接触地面的情况下轻提脚跟，交替感受支撑。",
                  cues: ["两脚站稳，交替轻提一侧脚跟", "把重量平稳交给另一侧", "脚踝和膝盖保持自然方向，不做强行旋转"],
                  commonMistakes: ["双脚同时离地变成跳跃", "在脚不动时扭转膝盖"],
                  bpmMin: 70, bpmMax: 105, prerequisites: ["house-jack"])
    ]

    public static func move(id: String) -> DanceMove? { moves.first { $0.id == id } }
    public static func moves(for style: DanceStyle, level: Int = 1) -> [DanceMove] {
        moves.filter { $0.style == style && $0.level <= level }
    }
}
